  name: CI/CD para projeto editor

  on:
    push:
      branches: [ main ]

  jobs:
      build-and-test:
       runs-on: ubuntu-latest

      steps:
          - name: Install Node.js
            uses: actions/setup-node@v3
            with:
              node-version: '16'

          - name: Install dependencies
            run: npm install

          - name: Run tests
            run: npm test

          - name: Build production bundle
            run: npm run build
